import '../models/expense.dart';
import '../models/budget.dart';
import '../constants/app_constants.dart';
import 'api_service.dart';

class ExpenseService {
  static ExpenseService? _instance;
  static ExpenseService get instance => _instance ??= ExpenseService._();
  
  final ApiService _apiService = ApiService();
  
  ExpenseService._();

  Future<List<Expense>> getExpenses() async {
    return await _apiService.getExpenses();
  }

  Future<Expense?> addExpense(Expense expense) async {
  return await _apiService.addExpense(expense);
}

  Future<void> deleteExpense(int expenseId) async {
    await _apiService.deleteExpense(expenseId);
  }

  Future<void> updateExpense(Expense updatedExpense) async {
    await _apiService.updateExpense(updatedExpense);
  }

  Future<double> getTotalExpenses() async {
    final expenses = await getExpenses();
    return expenses.fold<double>(
      0.0,
      (double sum, Expense expense) => sum + expense.amount,
    );
  }

  Future<Map<String, double>> getExpensesByCategory() async {
    final expenses = await getExpenses();
    final Map<String, double> categoryTotals = {};
    
    for (final expense in expenses) {
      categoryTotals[expense.category] = 
          (categoryTotals[expense.category] ?? 0) + expense.amount;
    }
    
    return categoryTotals;
  }

  // Budget Management
  Future<double?> getBudget(int year, int month) async {
    final budgets = await _apiService.getBudgets();
    final monthKey = _getMonthKey(year, month);
    
    for (final budget in budgets) {
      if (budget.month == monthKey) {
        return budget.amount;
      }
    }
    return null;
  }

  Future<void> setBudget(int year, int month, double amount) async {
    final monthKey = _getMonthKey(year, month);
    final budget = Budget(
      id: 0, // ID will be generated by the backend
      month: monthKey,
      amount: amount,
      spent: 0.0,
    );
    await _apiService.createOrUpdateBudget(budget);
  }

  Future<void> clearBudget(int year, int month) async {
    final monthKey = _getMonthKey(year, month);
    final budgets = await _apiService.getBudgets();
    
    for (final budget in budgets) {
      if (budget.month == monthKey) {
        // Set amount to 0 to clear the budget
        final clearedBudget = Budget(
          id: budget.id,
          month: budget.month,
          amount: 0.0,
          spent: budget.spent,
        );
        await _apiService.createOrUpdateBudget(clearedBudget);
        break;
      }
    }
  }

  String _getMonthKey(int year, int month) {
    // Format: "July 2026"
    final months = [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ];
    return '${months[month - 1]} $year';
  }
}
